[env]
framework = arduino
monitor_speed = 115200

[env:uno]
platform = atmelavr
board = uno

[env:leonardo]
platform = atmelavr
board = leonardo

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
build_flags = -DUSB_MIDI
